CC=gcc

password-crack: password-crack.c sha-256.c
	$(CC) -fopenmp -o password-crack.exe password-crack.c sha-256.c

password-crack-soln: password-crack-soln.c sha-256.c
	$(CC) -fopenmp -o password-crack-soln.exe password-crack-soln.c sha-256.c
